server:
  port: 18080
  ssl:
    key-store: classpath:server.jks
    key-store-password: 0e493bprf92z
    key-store-type: JKS

web:
  # 上传路径
  upload-path: /www/upload/
# Spring配置
spring:
  web:
    resources:
      # 静态资源位置
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      # 上传单文件最大大小
      max-file-size: 100MB
      # 最大请求大小
      max-request-size: 1000MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 数据库信息
      url: jdbc:mysql://cdb-csf20mte.cd.tencentcdb.com:10099/nearby
      username: root
      password: ********
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 最长等待时间
      max-wait: 60000
      # 检测空闲连接的间隔时间（单位为 ms）
      time-between-eviction-runs-millis: 60000
      # 连接在池中的最短生存时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中的最长生存时间
      max-evictable-idle-time-millis: 900000
      # 检查连接是否有效的 SQL 语句
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: zxchen
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 2000
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 日志配置
logging:
  level:
    com.zxchen: info
    org.springframework: warn

# MyBatis配置
mybatis:
  type-aliases-package: com.zxchen.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-handlers-package: com.zxchen.**.enums.handler

# Token鉴权配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 60

# 腾讯云配置
qcloud:
  # 密钥配置
  secret:
    id: ********
    key: ********
  # COS配置
  cos:
    # 临时签名配置
    sts:
      # 临时签名有效期（秒）
      duration: 1800
    # 存储桶
    bucket: zxchen-1301844697
    region: ap-chengdu
  # MySQL配置
  mysql:
    # NGram分词大小
    ngram-token-size: 2
  # 短信配置
  sms:
    # SDK AppID
    app-id: 1400609106
    verification-code-length: 4
    modify-phone:
      template-id: 1290689



# 对项目的缓存进行配置
cache:
  # 缓存有效期配置
  time:
    # 用户简要信息的缓存时长（单位为分钟）
    user-info: 60

# SnowFlake算法相关配置
snowflake:
  # 机房ID
  datacenter-id: 10
  # 机器ID
  worker-id: 10
